### ISSUE TITLE
Button on videos page not visible

### ISSUE THREAD

**Issue by SarahMohamed96** [TheGreatShazly/Scrumbledores-Army#1]
1. low severity
2. Sarah Mohamed
3. When video loads on the videos page, the button isn't visible to the user and there's no way to scroll down
4. Open videos page
5. User should see what the button does/what's written on the button

**Comment by seifhussam** [comment]
What are the buttons that the user should see ? 
![screenshot from 2017-05-01 14-41-55](https://cloud.githubusercontent.com/assets/19639272/25579938/95a06bde-2e7c-11e7-927e-bc20bb7c4151.png)

**Comment by SarahMohamed96** [comment]
The button wasn't visible on my computer but then I checked on someone else's computer and it was visible, sorry, my bad :)
